parcel/urls.py
from django.conf.urls import url
from django.views.generic import ListView, CreateView, DeleteView, UpdateView

from parcel.forms import ParcelAdminForm
from parcel.models import Parcel
from parcel.views import queryParcelOwners, packageQuickStore 
from sabot.decorators import user_is_finance, user_is_staff
from sabot.multiYear import getActiveYear, YSCreateView
from sabot.views import MultipleListView
from sponsor.models import Sponsoring

urlpatterns = [
	url(r'^list/?',
		user_is_staff(MultipleListView.as_view(
			template_params = {
				"object_list" :
					lambda req, kwargs : Sponsoring.objects.filter(year=getActiveYear(req)).select_related(),
				"parcel_list" :
					lambda req, kwargs : Parcel.objects.filter(year=getActiveYear(req)).select_related(),
			},
			template_name = "parcel/admin/list.html")),
		name = "parcel_list"),
	url(r'^new',
		user_is_staff(YSCreateView.as_view(
			model = Parcel,
			form_class = ParcelAdminForm,
			template_name = "parcel/admin/update.html",
			success_url = "parcel_list")),
		name = "parcel_new"),
	url(r'^(?P<pk>[0-9]+)$',
		user_is_staff(UpdateView.as_view(
			model = Parcel,
			form_class = ParcelAdminForm,
			template_name = "parcel/admin/update.html",
			success_url = "list")),
		name = "parcel_update"),
	url(r'^del/(?P<pk>[0-9]+)$',
		user_is_staff(DeleteView.as_view(
			model = Parcel,
			template_name= "parcel/admin/del.html",
			success_url="../list")),
		name = "parcel_del"),
	url(r'query_owners',
		user_is_staff(queryParcelOwners),
		name = "parcel_query_owners"),
	url(r'quick_store',
		user_is_staff(packageQuickStore),
		name = "parcel_quick_store"),
]

sabot/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from main.views import OverviewView, WayfinderView
from sabot.multiYear import setActiveYearView

from djangosaml2 import views as djangosaml2_views

urlpatterns = [
############# PORTAL PAGE #################

	url(r"^$", 	login_required(WayfinderView.as_view()), name = "homepage"),
	url(r"^overview$",
		login_required(OverviewView.as_view(
			template_name = "main/homepage.html")),
		name = "overview"),
	url(r"^faq$", TemplateView.as_view(template_name="sponsor/publicFaqPage.html")),

########## MULTIYEAR SUPPORT #############
	url(r"^setYear/(?P<year>\d{4})$", login_required(setActiveYearView)),

############ INCLUDE APPS ################
	url(r'^accounts/', include('account.urls')),
	url(r'^accounts/', include('registration.backends.model_activation.urls')),

	url(r'^sponsors/', include('sponsor.urls_sponsors')),
	url(r'^parcel/', include('parcel.urls')),
	url(r'^sponsorcontacts/', include('sponsor.urls_sponsorcontacts')),
	url(r'^sponsorpackages/', include('sponsor.urls_sponsorpackages')),
	url(r'^sponsordjangotemplates/', include('sponsor.urls_sponsordjangotemplates')),
	url(r'^sponsormails/', include('sponsor.urls_sponsormails')),
	url(r'^sponsormailattachments/', include('sponsor.urls_sponsormailattachments')),
	url(r'^projects/', include('project.urls')),
	url(r'^devrooms/', include('devroom.urls')),
	#url(r'^ticket/', include('ticket.urls')),
	url(r'^documenttemplate/', include('invoice.urls_documenttemplate')),
	url(r'^invoice/', include('invoice.urls_invoice')),
	url(r'^saml2/', include('djangosaml2.urls')),
	url(r'^saml2test/', djangosaml2_views.echo_attributes, name='echo_attributes'),
	url(r"^logged_out$", TemplateView.as_view(template_name="registration/logout.html")),
	url(r'^i18n/', include('django.conf.urls.i18n')),
]

if settings.LOCAL:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	from django.contrib.staticfiles.urls import staticfiles_urlpatterns
	urlpatterns += staticfiles_urlpatterns()

invoice/models.py
import datetime
from decimal import Decimal
import os


from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _

from invoice import odtemplate
from sabot.utils import random_filename_upload
import sponsor.models

class DocumentTemplate(models.Model):
	DOC_CHOICES = (
		('INVOICE', _("Invoice template")),
		('OFFER', _("Offer template"))
	)

	description = models.CharField(max_length=128, verbose_name=_("Description for the invoice template"))
	template = models.FileField(upload_to=random_filename_upload("invoice_templates"), verbose_name=_("Invoice template file (odt)"))
	docType = models.CharField(max_length=16, choices=DOC_CHOICES, verbose_name=_("Type of this document template"))



	def __unicode__(self):
		return self.description

class YearlyInvoiceCounters(models.Model):
	year = models.PositiveIntegerField(verbose_name=_("The year this counter belongs to"))
	counter = models.PositiveIntegerField(verbose_name=_("The current counter value"))

	@classmethod
	def get_next_counter(cls):
		# check if a counter for this year already exists
		try:
			cntr = cls.objects.get(year=datetime.date.today().year)
		except cls.DoesNotExist:
			cntr = cls(year=datetime.date.today().year,counter=0)
			cntr.save()
		return cntr.counter+1

	@classmethod
	def update_counter(cls,new_max):
		try:
			cntr = cls.objects.get(year=datetime.date.today().year)
		except cls.DoesNotExist:
			cntr = cls(year=datetime.date.today().year,counter=new_max)
		cntr.counter=new_max
		cntr.save()

class Invoice(models.Model):
	invoiceNumber = models.CharField(max_length=64, unique=True, db_index=True, verbose_name=_("Invoice number"))
	invoiceAmount = models.DecimalField(max_digits=32, decimal_places=2, editable=False, verbose_name=_("Invoice amount"))
	creationDate = models.DateField(auto_now_add=True, editable=False, verbose_name=_("Creation date"))
	dueDate = models.DateField(verbose_name=_("Due date"))
	payed = models.BooleanField(default=False, editable=False, verbose_name=_("This invoice is payed."))
	sponsoring = models.OneToOneField(sponsor.models.Sponsoring, editable=False, related_name="invoice", verbose_name=_("Sponsoring package belonging to this invoice"))
	pdf = models.FileField(upload_to="skinvoices", blank=True, null=True, editable=False, verbose_name=_("Invoice pdf"))
	template = models.ForeignKey(DocumentTemplate,null=True, on_delete=models.SET_NULL, verbose_name=_("Template to use for this invoice"))
	rtTicketRef = models.PositiveIntegerField(blank=True, null=True, editable=False, verbose_name=_("RT Ticket reference for sending this invoice"))

	class PDFRenderingError(Exception):
		pass

	def getInvoiceFilename(self):
		return "{}.pdf".format(self.invoiceNumber.replace("/","_"))

	def render_pdf(self):
		if self.sponsoring.billingReferenceOptOut:
			billRef = str(self.sponsoring.id)
		else:
			billRef = self.sponsoring.billingReference
		context = {
			"POSTAL_ADDRESS" : self.sponsoring.getBillingAddress(),
			"INVOICE_NUMBER" : self.invoiceNumber,
			"INVOICE_REF" : billRef,
			"DUE_DATE" : self.dueDate.strftime("%d.%m.%Y"),
			"PACKAGE_NAME" : self.sponsoring.package.name,
			"PACKAGE_DESCRIPTION" : "\n".join(self.sponsoring.getPacketDescription()),
			"VAT" : str(settings.INVOICE_VAT),
			"PRICE_NET" : str(self.sponsoring.package.price.quantize(Decimal("0.01"))),
			"PRICE_GROSS" : str(self.sponsoring.package.getPriceGross()),
			"VAT_TOTAL" : str(self.sponsoring.package.getVATAmount()),
		}
		temp = odtemplate.ODTTemplate(self.template.template.path)
		temp.render(context)
		if not os.path.exists(settings.MEDIA_ROOT + "invoice_pdfs"):
			os.mkdir(settings.MEDIA_ROOT + "invoice_pdfs")
		pdfpath = settings.MEDIA_ROOT + "invoice_pdfs/" + self.getInvoiceFilename()
		temp.savePDF(pdfpath)
		self.pdf.name = "invoice_pdfs/" + self.getInvoiceFilename()
		self.save()

class SMSKaufenSnailMailJob(models.Model):
	sponsoring = models.OneToOneField(sponsor.models.Sponsoring, related_name="snailmailinvoice", verbose_name=_("Sponsoring package belonging to this snail mailing job"))
	jobid = models.PositiveIntegerField(verbose_name=_("SMSKaufen job identifier"))
	joberror = models.CharField(max_length=256, blank=True, verbose_name=_("Error description of a potential processing error"))
	success = models.BooleanField(default=False, verbose_name=_("The mail was successfully sent."))

invoice/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit, Div, HTML
from crispy_forms.bootstrap import FormActions, StrictButton, TabHolder, Tab, AppendedText, PrependedText

from invoice.models import Invoice, DocumentTemplate


class InvoiceForm(forms.ModelForm):
	class Meta:
		model = Invoice
		exclude = ()

	template = forms.ModelChoiceField(queryset=DocumentTemplate.objects.filter(docType="INVOICE"), label=_("Template to use for this invoice"))
	dueDate = forms.DateField(label=_("Due date"), input_formats=["%d.%m.%Y", "%d.%m.%y"], widget=forms.DateInput(format="%d.%m.%Y"))

	def __init__(self, *args, **kwargs):
		super(InvoiceForm, self).__init__(*args, **kwargs)
		# change the invoice number field so that it isn't required anymore
		self.fields["invoiceNumber"].required = False
		self.fields["invoiceNumber"].label = _("Invoice number (leave empty to auto-generate one)")

		self.helper = FormHelper()
		self.helper.layout = Layout(
			Field("invoiceNumber"),
			Field("dueDate"),
			Field("template"),
		)
		self.helper.add_input(Submit("Create invoice", "Create invoice"))


class OfferForm(forms.Form):
	template = forms.ModelChoiceField(queryset=DocumentTemplate.objects.filter(docType="OFFER"), label=_("Template to use for this offer"))

templates/invoice/documenttemplate/del.html
{% extends "master.html" %}

{% block content %}
<div class="page-header">
	<h2>Confirm deletion</h2>
</div>
<div class="row">
<div class="col-md-3 centerbox">
		<form method="POST">
			{% csrf_token %}
			Do you really want to remove the invoice template {{object.description}}?
			<br />
			Please note that this does not remove already created invoices with this template. However, they cannot be recreated any longer with this template.
			{{form.as_p}}
			<div class="form-actions">
				<button type="Submit" class="btn btn-danger">Delete</button>
				<a href="{% url 'documenttemplate_list' %}" class="btn">Cancel</a>
			</div>
		</form>
	</div>
</div>
{% endblock %}

templates/invoice/documenttemplate/list.html
{% extends "master.html" %}
{% block content %}

<div class="page-header">
	<h2>List of invoice templates</h2>
</div>


<ul class="nav nav-pills">
	<li><a href="{% url 'documenttemplate_new' %}"><span class="glyphicon glyphicon-plus"></span> Add a new invoice template</a></li>
</ul>
<table class="table table-striped table-bordered table-hover tablesorter">
	<thead>
		<tr>
			<th>Description</th>
			<th>File</th>
			<th>Document type</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		{% for tmpl in object_list %}
			<tr>
				<td>{{tmpl.description}}</td>
				<td><a href="{{tmpl.template.url}}" data-toggle="tooltip" title="Download template file."><span class="glyphicon glyphicon-download"></span></a></td>
				<td>{{tmpl.get_docType_display}}</td>
				<td>
					<a href="{% url 'documenttemplate_update' pk=tmpl.pk %}" data-toggle="tooltip" title="Edit this invoice template"><span class="glyphicon glyphicon-edit"></span></a>
					<a href="{% url 'documenttemplate_del' pk=tmpl.pk %}" data-toggle="tooltip" title="Delete this invoice template"><span class="glyphicon glyphicon-remove"></span></a>
				</td>
			</tr>
		{% endfor %}
	</tbody>

</table>
<script>
</script>

{% endblock %}

templates/invoice/documenttemplate/update.html
{% extends "master.html" %}
{% load formstyle %}
{% block content %}

<div class="page-header">
	{% if object %}
	<h2>Edit invoice template</h2>
	{% else %}
	<h2>Create a new invoice template</h2>
	{% endif %}
</div>


<ul class="nav nav-pills">
	<li><a href="{% url 'documenttemplate_list' %}"><span class="glyphicon glyphicon-arrow-left"></span> List of invoice templates</a></li></ul>

{% if object %}
	{% simple_crispy form "Save" %}
{% else %}
	{% simple_crispy form "Create" %}
{% endif %}



{% endblock %}