parcel/urls.py
from django.conf.urls import url
from django.views.generic import ListView, CreateView, DeleteView, UpdateView

from parcel.forms import ParcelAdminForm
from parcel.models import Parcel
from parcel.views import queryParcelOwners, packageQuickStore 
from sabot.decorators import user_is_finance, user_is_staff
from sabot.multiYear import getActiveYear, YSCreateView
from sabot.views import MultipleListView
from sponsor.models import Sponsoring

urlpatterns = [
	url(r'^list/?',
		user_is_staff(MultipleListView.as_view(
			template_params = {
				"object_list" :
					lambda req, kwargs : Sponsoring.objects.filter(year=getActiveYear(req)).select_related(),
				"parcel_list" :
					lambda req, kwargs : Parcel.objects.filter(year=getActiveYear(req)).select_related(),
			},
			template_name = "parcel/admin/list.html")),
		name = "parcel_list"),
	url(r'^new',
		user_is_staff(YSCreateView.as_view(
			model = Parcel,
			form_class = ParcelAdminForm,
			template_name = "parcel/admin/update.html",
			success_url = "parcel_list")),
		name = "parcel_new"),
	url(r'^(?P<pk>[0-9]+)$',
		user_is_staff(UpdateView.as_view(
			model = Parcel,
			form_class = ParcelAdminForm,
			template_name = "parcel/admin/update.html",
			success_url = "list")),
		name = "parcel_update"),
	url(r'^del/(?P<pk>[0-9]+)$',
		user_is_staff(DeleteView.as_view(
			model = Parcel,
			template_name= "parcel/admin/del.html",
			success_url="../list")),
		name = "parcel_del"),
	url(r'query_owners',
		user_is_staff(queryParcelOwners),
		name = "parcel_query_owners"),
	url(r'quick_store',
		user_is_staff(packageQuickStore),
		name = "parcel_quick_store"),
]

sabot/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from main.views import OverviewView, WayfinderView
from sabot.multiYear import setActiveYearView

from djangosaml2 import views as djangosaml2_views

urlpatterns = [
############# PORTAL PAGE #################

	url(r"^$", 	login_required(WayfinderView.as_view()), name = "homepage"),
	url(r"^overview$",
		login_required(OverviewView.as_view(
			template_name = "main/homepage.html")),
		name = "overview"),
	url(r"^faq$", TemplateView.as_view(template_name="sponsor/publicFaqPage.html")),

########## MULTIYEAR SUPPORT #############
	url(r"^setYear/(?P<year>\d{4})$", login_required(setActiveYearView)),

############ INCLUDE APPS ################
	url(r'^accounts/', include('account.urls')),
	url(r'^accounts/', include('registration.backends.model_activation.urls')),

	url(r'^sponsors/', include('sponsor.urls_sponsors')),
	url(r'^parcel/', include('parcel.urls')),
	url(r'^sponsorcontacts/', include('sponsor.urls_sponsorcontacts')),
	url(r'^sponsorpackages/', include('sponsor.urls_sponsorpackages')),
	url(r'^sponsordjangotemplates/', include('sponsor.urls_sponsordjangotemplates')),
	url(r'^sponsormails/', include('sponsor.urls_sponsormails')),
	url(r'^sponsormailattachments/', include('sponsor.urls_sponsormailattachments')),
	url(r'^projects/', include('project.urls')),
	url(r'^devrooms/', include('devroom.urls')),
	#url(r'^ticket/', include('ticket.urls')),
	url(r'^documenttemplate/', include('invoice.urls_documenttemplate')),
	url(r'^invoice/', include('invoice.urls_invoice')),
	url(r'^saml2/', include('djangosaml2.urls')),
	url(r'^saml2test/', djangosaml2_views.echo_attributes, name='echo_attributes'),
	url(r"^logged_out$", TemplateView.as_view(template_name="registration/logout.html")),
	url(r'^i18n/', include('django.conf.urls.i18n')),
]

if settings.LOCAL:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	from django.contrib.staticfiles.urls import staticfiles_urlpatterns
	urlpatterns += staticfiles_urlpatterns()

sponsor/models.py
# -*- coding: utf-8 -*-
from decimal import Decimal, localcontext, ROUND_HALF_EVEN
import datetime
import re

from django.conf import settings
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _

from sabot.utils import random_filename_upload

class SponsorMailAttachment(models.Model):
	name = models.CharField(max_length=128, verbose_name=_("Displayed attachment file name"))
	attachment = models.FileField(upload_to="sponsormail_attachments", verbose_name=_("The contact mail attachment"))

	def __unicode__(self):
		return self.name

class SponsorMailTemplate(models.Model):
	templateName = models.CharField(max_length=128, verbose_name=_("Template name"))
	template = models.TextField(verbose_name=_("Django template content"))

	def __unicode__(self):
		return self.templateName


class SponsorMail(models.Model):
	mailTemplateName = models.CharField(max_length=128, verbose_name=_("Mail template name"))
	template = models.ForeignKey(SponsorMailTemplate, on_delete=models.SET_NULL, null=True, verbose_name=_("Mail text template"))
	mailSubject = models.CharField(max_length=256, verbose_name=_("E-mail subject"))
	attachments = models.ManyToManyField(SponsorMailAttachment,blank=True)

	def __unicode__(self):
		return self.mailTemplateName

class SponsorContact(models.Model):
	class Meta:
		ordering = ["companyName"]

	GENDER_CHOICES = (
		('M', 'Male'),
		('F', 'Female'),
	)
	LANGUAGE_CHOICES = (
		("de-DE", "German"),
		("en-US", "English"),
	)
	companyName = models.CharField(max_length=128, verbose_name=_("Company name"))
	contactEMail = models.EmailField(verbose_name=_("General contact mail"))
	address2 = models.CharField(blank=True,max_length=128, verbose_name=_("Address addition"))
	street = models.CharField(max_length=128, verbose_name=_("Street"))
	zipcode = models.CharField(max_length=16, verbose_name=_("ZIP Code")) # this is a char field to stay flexible for foreign addresses
	city = models.CharField(max_length=64, verbose_name=_("City"))
	country = models.CharField(blank=True, max_length=64, verbose_name=_("Country"))
	responded = models.BooleanField(verbose_name=_("This sponsor did react to our contact attempt"),default=False)
	contactPersonFirstname = models.CharField(blank=True,max_length=128, verbose_name=_("Contact person firstname"))
	contactPersonSurname = models.CharField(blank=True,max_length=128, verbose_name=_("Contact person surname"))
	contactPersonGender = models.CharField(max_length=1,blank=True, choices=GENDER_CHOICES, verbose_name=_("Gender of contact person"))
	contactPersonLanguage = models.CharField(max_length=16, choices=LANGUAGE_CHOICES, verbose_name=_("Language of contact person"), default="de-DE")
	contactPersonEmail = models.EmailField(blank=True, verbose_name=_("Contact person email"))

	comment = models.TextField(blank=True, verbose_name=_("Comments and Notes"))
	template = models.ForeignKey(SponsorMail,blank=True, null=True, verbose_name=_("Mail contact template"))

	lastMailed = models.DateField(blank=True,null=True,editable=False, verbose_name=_("Last time we mailed this contact"))
	rtTicketId = models.PositiveIntegerField(blank=True, null=True, editable=False, verbose_name=_("RT ticket id"))

	def allDataAvailable(self):
		return (self.companyName != ""
			and self.contactPersonEmail != ""
			and self.street != ""
			and self.zipcode != "" and self.zipcode != "0"
			and self.city != ""
			and self.contactPersonFirstname != ""
			and self.contactPersonSurname != ""
			and self.contactPersonEmail != ""
			and self.template is not None)

	def wasRecentlyMailed(self):
		if self.lastMailed == None:
			return False
		timedelta = datetime.date.today() - self.lastMailed
		if timedelta.days < 31:
			return True
		return False

	def __unicode__(self):
		return self.companyName


class SponsorPackage(models.Model):
	name = models.CharField(max_length=128, verbose_name=_("Package name"))
	comments = models.TextField(blank=True, verbose_name=_("Comments"))
	color = models.CharField(default="#ffffff", max_length=7, verbose_name=_("Display color of sponsor package"), validators=[ RegexValidator(regex=r"#[0-9a-f]{6}", message = _("Please enter a HTML color code of format #[0-9a-f]{6}")) ] )

	# the properties of this package
	logoWebsitePositionDE = models.CharField(blank=True, max_length=256, verbose_name=_("Description text for the logo position on our website (German)"))
	logoWebsitePositionEN = models.CharField(blank=True, max_length=256, verbose_name=_("Description text for the logo position on our website (English)"))
	hasHpText = models.BooleanField(default=False,verbose_name=_("Has the sponsor texts on our homepage?"))
	hasLogoOnPrintmedia = models.BooleanField(default=False, verbose_name=_("Is the sponsor's logo shown on all our printed media?"))
	hasSocialMedia = models.BooleanField(default=True, verbose_name=_("Has the sponsor social media advertising?"))
	hasConferenceBagContent = models.BooleanField(default=False, verbose_name=_("Has the sponsor the option to send us contents for the conference bag?"))
	hasBooth = models.BooleanField(default=False,verbose_name=_("Has the sponsor the option for a booth on the conference?"))
	boothPositionEN = models.CharField(blank=True, max_length=256, verbose_name=_("Position of booth for packet description. This text gets printed in the description. Leave empty to just generate an generic item. (EN)"))
	boothPositionDE = models.CharField(blank=True, max_length=256, verbose_name=_("Position of booth for packet description (DE)"))
	hasProgramAd = models.BooleanField(default=False,verbose_name=_("Has the sponsor an advertisement in the printed program?"))
	programAdInfo = models.TextField(blank=True,verbose_name=_("Displayed information about the size, quality, color, etc on the printed advertisement"))
	programAdInfoDescEN = models.CharField(blank=True, max_length=256, verbose_name=_("Information about advertisement in our program for the packet description (EN)"))
	programAdInfoDescDE = models.CharField(blank=True, max_length=256, verbose_name=_("Information about advertisement in our program for the packet description (DE)"))
	hasPackets = models.BooleanField(default=False,verbose_name=_("Is the sponsor allowed to send packets to us?"))
	hasParticipants = models.BooleanField(default=False,verbose_name=_("Has the sponsor the option to register VIPs? (usually for booth)"))
	hasProgramAdText = models.BooleanField(default=False,verbose_name=_("Has the sponsor an advertisement text in the printed program?"))
	hasRecruitingEvent = models.BooleanField(default=False,verbose_name=_("Has the sponsor the option to participate in the recruting event?"))
	programAdTextNumWords = models.PositiveIntegerField(blank=True,null=True, verbose_name=_("How many words is the advertisement text allowed to have?"))
	numFreeTickets = models.PositiveIntegerField(default=0, verbose_name=_("How many free tickets gets this sponsor?"))
	price = models.DecimalField(max_digits=32, decimal_places=2, verbose_name=_("Package price"))
	countPackages = models.PositiveIntegerField(default=0, verbose_name=_("How many packages of this type do we sell?"))
	additionalContentTextDE = models.TextField(blank=True,verbose_name=_("Additional package contents (German). See English"))
	additionalContentTextEN = models.TextField(blank=True,verbose_name=_("Additional package content (English). Additional items that belong to this package but are not automatically generated from the selections above."))
	hpCatagoryName = models.CharField(max_length=128,verbose_name=_("Homepage Catagory"))

	year = models.PositiveIntegerField(editable=False, verbose_name=_("Conference year this package belongs to"))

	def getPriceGross(self):
		with localcontext() as ctx:
			ctx.rounding = ROUND_HALF_EVEN

			vatPercent = Decimal(settings.INVOICE_VAT) * Decimal("0.01")
			grossPrice = self.price + (self.price * vatPercent)
			return grossPrice.quantize(Decimal("0.01"))

	def getVATAmount(self):
		with localcontext() as ctx:
			ctx.rounding = ROUND_HALF_EVEN

			vatPercent = Decimal(settings.INVOICE_VAT) * Decimal("0.01")
			vatAmount = self.price * vatPercent
			return vatAmount.quantize(Decimal("0.01"))


	def countSponsorings(self):
		return self.sponsorings.count()

	def countCommitedSponsorings(self):
		return self.sponsorings.filter(commitment=True).count()

	def __unicode__(self):
		return self.name

	def getPackageDescriptionDE(self):
		return self._getPackageDescription(self.sponsorPackageDescriptionDE)

	def getPackageDescriptionEN(self):
		return self._getPackageDescription(self.sponsorPackageDescriptionEN)

	def _getPackageDescription(self, desc):
		items = []
		# iterate through the description dictionary and append all the results to items
		for k, v in desc:
			if callable(k):
				res = k(self)
			else:
				res = getattr(self, k)
			if res:
				if callable(v):
					content = v(self)
					if isinstance(content, (list, tuple)):
						items.extend(content)
					else:
						items.append(content)
				else:
					items.append(v)
		return items

	sponsorPackageDescriptionDE = [
		("hasBooth", lambda s : s.boothPositionDE if len(s.boothPositionDE) > 0 else u"Ausstellungsplatz"),
		("hasRecruitingEvent", u"Stand auf der Recruitingsession"),
		("hasConferenceBagContent", u"Informationsmaterial in den Konferenztaschen"),
		( lambda s : True, lambda s : s.logoWebsitePositionDE),
		( "hasLogoOnPrintmedia", u"Logopräsenz auf allen Werbemitteln (z. B. Badges, Besucherflyer, Plakat)"),
		( "hasSocialMedia", u"Namentliche Erwähnung auf unseren SocialMedia Kanälen (Twitter, Facebook, G+)"),
		( "hasProgramAd", lambda s : u"Anzeige im Konferenzprogramm ({})".format(s.programAdInfoDescDE)),
		( "hasProgramAdText", lambda s : u"Text im Konferenzprogramm ({} Wörter)".format(s.programAdTextNumWords)),

templates/sponsor/sponsoring/list.html
{% extends "master.html" %}
{% load sponsor %}
{% load crispy_forms_tags %}
{% block content %}

<div class="page-header">
	<h2>List of sponsors</h2>
</div>
<ul class="nav nav-pills" style="margin-bottom:20px">
	<li class="pull-right"><a href="{% url 'sponsor_export_json' %}" data-toggle="tooltip" title="Download sponsor data as JSON">JSON export</a></li>
	<li class="pull-right"><a href="{% url 'sponsor_export_xml' %}" data-toggle="tooltip" title="Download sponsor data as XML">XML export</a></li>
	<li class="pull-right"><a href="{% url 'sponsor_export_logos' %}" data-toggle="tooltip" title="Download all sponsor logos in an archive">Logo bulk export</a></li>
	<li class="pull-right"><a href="{% url 'sponsor_export_programad' %}" data-toggle="tooltip" title="Download all program advertisements in an archive">Ad bulk export</a></li>
	<li class="pull-right">
		<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Export mail <span class="caret"></span></a>
		<ul class="dropdown-menu">
			<li><a href="{% url 'sponsor_export_adminmail' %}">Organizers</a></li>
			<li><a href="{% url 'sponsor_export_allmail' %}">All participants</a></li>
			<li><a href="{% url 'sponsor_export_boothmail' %}">Booth personnel</a></li>
			<li><a href="{% url 'sponsor_export_recruitingmail' %}">Recruiting personnel</a></li>
		</ul>
	</li>
</ul>
<p class="text-info"><span class="glyphicon glyphicon-circle-arrow-right"></span>Add a new sponsor from the list of <a href="{% url 'sponsorcontact_list' %}">sponsoring contacts</a></p>
{% if moneyRaised %}
	<div class="bs-callout bs-callout-success">
		<h4>Money raised</h4>
		<p><strong>{{moneyRaised}}€</strong></p>
	</div>
{% endif  %}
<div class="table-container">
<div class="filter-tools" style="display: none">
	<span class="glyphicon glyphicon-filter" style="margin-right: 15px"></span>
	<form class="form-inline">
		<div class="form-group">
			<label for="filterByPacket">Packets</label>
			<select class="form-control" id="filterByPacket">
			</select>
		</div>
		<div class="form-group">
			<div class="checkbox">
				<label for="filterBooth">
					<input class="checkboxinput checkbox" id="filterBooth" type="checkbox" data-filter="booth"> with booth
				</label>
			</div>
		</div>
		<div class="form-group">
			<div class="checkbox">
				<label for="filterRecruiting">
					<input class="checkboxinput checkbox" id="filterRecruiting" type="checkbox" data-filter="recruiting"> with recruiting
				</label>
			</div>
		</div>
		<div class="form-group">
			<div class="checkbox">
				<label for="filterParcel">
					<input class="checkboxinput checkbox" id="filterParcel" type="checkbox" data-filter="parcel"> with parcel
				</label>
			</div>
		</div>
		<div class="form-group">
			<div class="checkbox">
				<label for="filterSocialMedia">
					<input class="checkboxinput checkbox" id="filterSocialMedia" type="checkbox" data-filter="socialmedia"> with social media
				</label>
			</div>
		</div>
	</form>

</div>
<table class="table table-bordered table-hover tablesorter">
	<thead>
		<tr>
			<th>Sponsor</th>
			<th>Display name</th>
			<th>RT</th>
			<th>Contact</th>
			<th>E-Mail</th>
			<th>Package</th>
			<th>Status</th>
			<th>Last modified</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		{% for sponsor in object_list %}
			<tr style="background-color: {% if sponsor.commitment %}{{sponsor.package.color}}{% else %}lightgrey{% endif %};">
				<td data-toggle="popover" data-html="true" data-trigger="hover" data-placement="top" data-content="{{sponsor.adminComment|linebreaksbr}}">{{sponsor.contact.companyName}}</td>
				<td>{{sponsor.displayCompanyName}}</td>
				<td>
					{% if sponsor.rtTicketId %}
						<a href="{{RT_TICKET_URL}}{{sponsor.rtTicketId}}">#{{sponsor.rtTicketId}}</a>
					{% endif %}
				</td>
				<td>{{sponsor.owner.first_name}} {{sponsor.owner.last_name}}</td>
				<td>{{sponsor.owner.email}}</td>
				<td class="sponsor-package-col"{%if sponsor.package.hasBooth %} data-hasbooth="1"{% endif %}{% if sponsor.package.hasRecruitingEvent %} data-hasrecruiting="1"{% endif %}{% if sponsor.package.hasPackets %} data-hasparcel="1"{% endif %} {% if sponsor.package.hasSocialMedia %} data-hassocialmedia="1"{% endif %}>
					<a href="{% url 'sponsorpackage_update' pk=sponsor.package.pk %}">{{sponsor.package}}</a>
				</td>
				<td>
					<a href="{% url 'sponsor_update' pk=sponsor.pk %}#billing-address" data-toggle="tooltip" title="Company billing address status"><span class="glyphicon glyphicon-euro {{sponsor.billingAddressStatus|statuscolorclass}}"></span></a>
					<a href="{% url 'sponsor_update' pk=sponsor.pk %}#general" data-toggle="tooltip" title="Company logo status"><span class="glyphicon glyphicon-picture {{sponsor.logoStatus|statuscolorclass}}"></span></a>
					<a href="{% url 'sponsor_update' pk=sponsor.pk %}#general" data-toggle="tooltip" title="Company weblink status"><span class="glyphicon glyphicon-share-alt {{sponsor.hpLinkStatus|statuscolorclass}}"></span></a>
					<a href="{% url 'sponsor_update' pk=sponsor.pk %}#social-media" data-toggle="tooltip" title="Company social media status"><span {% if sponsor.socialMediaAnnounced %}style="transform: rotate(-45deg)"{% endif %}class="glyphicon glyphicon-bullhorn {{sponsor.socialMediaStatus|statuscolorclass}}"></span></a>
					<a href="{% url 'sponsor_update' pk=sponsor.pk %}#froscon-homepage" data-toggle="tooltip" title="Status of texts for our homepage"><span class="glyphicon glyphicon-globe {{sponsor.hpTextStatus|statuscolorclass}}"></span></a>
					<a href="{% url 'sponsor_update' pk=sponsor.pk %}#booth" data-toggle="tooltip" title="Booth information status"><span class="glyphicon glyphicon-home {{sponsor.boothStatus|statuscolorclass}}"></span></a>
					<a href="{% url 'sponsor_update' pk=sponsor.pk %}#recruiting" data-toggle="tooltip" title="Recruiting session status"><span class="glyphicon glyphicon-resize-small {{sponsor.recruitingStatus|statuscolorclass}}"></span></a>
					<a href="{% url 'sponsor_update' pk=sponsor.pk %}#printed-program" data-toggle="tooltip" title="Program advertisment status"><span class="glyphicon glyphicon-file {{sponsor.programAdStatus|statuscolorclass}}"></span></a>
					<a href="{% url 'sponsor_update' pk=sponsor.pk %}#printed-program" data-toggle="tooltip" title="Program description text status"><span class="glyphicon glyphicon-align-left {{sponsor.programAdTextStatus|statuscolorclass}}"></span></a>
					<a href="{% url 'sponsor_update' pk=sponsor.pk %}#parcel" data-toggle="tooltip" title="Information on sent packets"><span class="glyphicon glyphicon-gift {{sponsor.packetsStatus|statuscolorclass}}"></span></a>
					<a href="{% url 'sponsor_participants' pk=sponsor.pk %}" data-toggle="tooltip" title="Participants status"><span class="glyphicon glyphicon-user {{sponsor.participantsStatus|statuscolorclass}}"></span></a>
					<td>{{sponsor.modifyDate|date:"j.n.Y"}}</td>
					<td>
						<a href="{% url 'sponsor_update' pk=sponsor.pk %}" data-toggle="tooltip" title="Edit sponsor information"><span class="glyphicon glyphicon-edit"></span></a>
						<a href="{% url 'sponsor_del' pk=sponsor.pk %}" data-toggle="tooltip" title="Delete this sponsor"><span class="glyphicon glyphicon-remove"></span></a>
						<a href="#" class="offerLink" data-sponsoring-id="{{sponsor.pk}}" data-toggle="tooltip" title="Generate an offer for this sponsoring"><span class="glyphicon glyphicon-print"></span></a>
					</td>
			</tr>
		{% endfor %}
	</tbody>
</table>
</div>

<div class="bs-callout bs-callout-info">
	<h4>Statistics</h4>
	<ul>
		<li>Booth: Yes: {{wantBooth}}, No: {{noBooth}}, Avail: {{canBooth}}</li>
		<li>Recruiting: Yes: {{wantRecruiting}}, No: {{noRecruiting}}, Avail: {{canRecruiting}}</li>
	</ul>
</div>

<div id="modal-offer-generator" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="Generate an offer" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h3>Generate an offer</h3>
			</div>
			<form id="offerGeneratorForm" method="POST">
				{% csrf_token %}
				<div class="modal-body">
					{{offerForm|crispy}}
				</div>
				<div class="modal-footer">
					<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
					<button class="btn btn-primary" id="odtButton">Download ODT</button>
					<button class="btn btn-primary" id="pdfButton">Download PDF</button>
				</div>
			</form>
		</div>
	</div>
</div>

<script>

function uniqueSort(arr) {
	var i,
	len = arr.length,
	out = [],
	obj = { };

	for (i = 0; i < len; i++) {
		obj[$.trim(arr[i])] = 0;
	}
	for (i in obj) {
		out.push(i);
	}
	return out.sort();
};

function reapplyFilters() {
	if (packageFilter != "") {
		$(".sponsor-package-col").filter(function () { return $.trim($(this).text()) == packageFilter;}).siblings().andSelf().slideDown();
		$(".sponsor-package-col").filter(function () { return $.trim($(this).text()) != packageFilter;}).siblings().andSelf().slideUp({ "queue" : false});
	}
	else {
		// we apply property based filtering
		var res = $(".sponsor-package-col");

		for (var prop in filters) {
			res = availableFilters[prop](res)
		}

		var toHide = $(".sponsor-package-col").not(res);
		res.siblings().andSelf().slideDown();
		toHide.siblings().andSelf().slideUp();
	}
}

function filtersToHash() {
	if (packageFilter != "") {
		location.hash = "package:" + packageFilter
	}
	else {
		if (Object.keys(filters).length > 0) {
			location.hash= Object.keys(filters).join("-");
		}
		else {
			location.hash = "";
		}
	}
}

function filtersFromHash() {
	filters = {}
	packageFilter = ""
	$("[data-filter]").prop("checked", false);
	$("#filterByPacket").val("all");
	if (location.hash != "") {
		var hash = decodeURIComponent(location.hash);
		if (hash.indexOf("#package:") === 0) {
			packageFilter = hash.split(":")[1];
			$("#filterByPacket").val(packageFilter);
		}
		else {
			res = hash.substring(1).split("-");
			res.forEach(function(val) { filters[val] = 1; $("[data-filter=" + val + "]").prop("checked", true); });
		}
	}
}

	var filters = {};
	var packageFilter = "";
	var availableFilters = {
		"booth" : function (res) { return res.filter(".sponsor-package-col[data-hasbooth]"); },
		"parcel" : function (res) { return res.filter(".sponsor-package-col[data-hasparcel]"); },
		"recruiting" : function (res) { return res.filter(".sponsor-package-col[data-hasrecruiting]"); },
		"socialmedia" : function (res) { return res.filter(".sponsor-package-col[data-hassocialmedia]"); }
	}

	$(document).ready(function () {
		$(".tablesorter").tablesorter({ sortList : [[0,0]], headers : { 6 : {sorter : false}, 7 : {sorter : "eudate"}, 8 : {sorter : false}}});
		$("[data-toggle=popover]").popover({ container : "body", delay : { show: 500, hide: 100 } });

		$(".filter-tools").show();
		// fill package select box with available packages
		var packages = uniqueSort($(".sponsor-package-col").map(function () { return $(this).text(); }).get());
		$("#filterByPacket").append($("<option/>", {
			value: "all",
			text: "(all)",
			}));
		$.each(packages, function(idx, item) {
			$("#filterByPacket").append($("<option/>", {
				value: item,
				text: item,
				}));
		});

		$("#filterByPacket").change(function () {
			var selector = $(this).val();
			if (selector == "all") {
				packageFilter = "";
			}
			else {
				packageFilter = selector;
			}
			filtersToHash();
		});

		$("[data-filter]").change(function () {
			packageFilter = "";
			if ($(this).is(":checked")) {
				filters[$(this).data("filter")] = 1;
			} else {
				delete filters[$(this).data("filter")];
			}
			filtersToHash();
		});

		$(window).on('hashchange', function () {
			filtersFromHash();
			reapplyFilters();
		});
		filtersFromHash();
		reapplyFilters();

		$(".offerLink").click(function (event) {
			event.preventDefault();
			$("#modal-offer-generator").data("sponsoring", $(this).data("sponsoringId"));
			$("#modal-offer-generator").modal();
		});
		$("#odtButton").click(function (event) {
			event.preventDefault();
			window.location.href = "/invoice/genoffer-odt/" + $("#modal-offer-generator").data("sponsoring") + "-" + $("#id_template").val();
			$("#modal-offer-generator").modal('hide');
		});
		$("#pdfButton").click(function (event) {
			event.preventDefault();
			window.location.href = "/invoice/genoffer-pdf/" + $("#modal-offer-generator").data("sponsoring") + "-" + $("#id_template").val();
			$("#modal-offer-generator").modal('hide');
		});
	});
</script>

{% endblock %}