exhibitor/urls.py
from django.conf.urls import include, url
from django.core.urlresolvers import reverse
from django.views.generic import ListView, DeleteView, CreateView, UpdateView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q, Sum

from exhibitor.forms import ExhibitorGeneralForm, ExhibitorDescriptionForm, ExhibitorBoothForm
from exhibitor.models import Exhibitor, ExhibitorParticipants
from sabot.decorators import user_is_staff
from sabot.multiYear import YSListView, YSXMLListView, YSOwnerSettingCreateView, getActiveYear
from sabot.views import ParticipantsView, OwnerSettingCreateView, PermCheckUpdateView, EmailOutputView, XMLListView, MultipleListView, PropertySetterView, PermCheckPropertySetterView, PermCheckSimpleDeleteView, ArchiveCreatorView


urlpatterns = [
	url(r'^new$',
		login_required(YSOwnerSettingCreateView.as_view(
			model = Exhibitor,
			form_class = ExhibitorGeneralForm,
			template_name = "exhibitor/create.html",
			success_url = "/exhibitors/{id}")),
		name="exhibitor_new"),
	url(r'^(?P<pk>[0-9]+)$',
		login_required(PermCheckUpdateView.as_view(
			model = Exhibitor,
			form_class = ExhibitorGeneralForm,
			template_name = "exhibitor/general.html",
			success_url = "/exhibitors/{id}")),
		name = "exhibitor_update_general"),
	url(r'^(?P<pk>[0-9]+)/description$',
		login_required(PermCheckUpdateView.as_view(
			model = Exhibitor,
			form_class = ExhibitorDescriptionForm,
			template_name = "exhibitor/description.html",
			success_url = "/exhibitors/{id}/description")),
		name = "exhibitor_update_texts"),
	url(r'^(?P<pk>[0-9]+)/booth$',
		login_required(PermCheckUpdateView.as_view(
			model = Exhibitor,
			form_class = ExhibitorBoothForm,
			template_name = "exhibitor/booth.html",
			success_url = "/exhibitors/{id}/booth")),
		name = "exhibitor_update_booth"),
	url(r'^(?P<pk>[0-9]+)/participants$',
		login_required(ParticipantsView.as_view(
			object_class = Exhibitor,
			connection_table_class = ExhibitorParticipants,
			template_name = "exhibitor/participants.html")),
		name="exhibitor_participants"),
	url(r'^(?P<pk>[0-9]+)/accept$',
		user_is_staff(PropertySetterView.as_view(
			model = Exhibitor,
			property_name = "accepted",
			property_value = True,
			next_view = "exhibitor_list")),
		name="exhibitor_accept"),
	url(r'^(?P<pk>[0-9]+)/unaccept$',
		user_is_staff(PropertySetterView.as_view(
			model = Exhibitor,
			property_name = "accepted",
			property_value = False,
			next_view = "exhibitor_list")),
		name="exhibitor_unaccept"),
	url(r'^participants/remove/(?P<pk>[0-9]+)$',
		login_required(PermCheckSimpleDeleteView.as_view(
			model = ExhibitorParticipants,
			permission_checker = lambda obj, user: obj.project.has_write_permission(user),
			redirect = lambda obj, kwargs: reverse("exhibitor_participants", kwargs = { "pk" : obj.project_id }) )),
		name="exhibitor_participants_delete"),
	url(r'^participants/makeadmin/(?P<pk>[0-9]+)$',
		login_required(PermCheckPropertySetterView.as_view(
			model = ExhibitorParticipants,
			permission_checker = lambda obj, user: obj.project.has_write_permission(user),
			property_name = "isAdmin",
			property_value = True,
			redirect = lambda obj, kwargs: reverse("exhibitor_participants", kwargs = { "pk" : obj.project_id }) )),
		name="exhibitor_participants_make_admin"),
	url(r'^participants/revokeadmin/(?P<pk>[0-9]+)$',
		login_required(PermCheckPropertySetterView.as_view(
			model = ExhibitorParticipants,
			permission_checker = lambda obj, user: obj.project.has_write_permission(user),
			property_name = "isAdmin",
			property_value = False,
			redirect = lambda obj, kwargs: reverse("exhibitor_participants", kwargs = { "pk" : obj.project_id }) )),
		name="exhibitor_participants_revoke_admin"),
	url(r'^list\+planning/?',
		user_is_staff(YSListView.as_view(
			queryset = Exhibitor.objects.select_related(),
			template_name = "exhibitor/list+planning.html")),
			name="exhibitor_list_planning"),
	url(r'^list/?',
		user_is_staff(YSListView.as_view(
			queryset = Exhibitor.objects.select_related(),
			template_name = "exhibitor/list.html")),
			name="exhibitor_list"),
	url(r'^del/(?P<pk>[0-9]+)$',
		user_is_staff(DeleteView.as_view(
			model = Exhibitor,
			template_name= "exhibitor/del.html",
			success_url="/exhibitors/list")),
			name="exhibitor_del"),
	url(r'^export/adminmail',
		user_is_staff(EmailOutputView.as_view(
			queryset = lambda req, kwargs : User.objects.filter(
				Q(exhibitorparticipants__isAdmin=True,
				  exhibitorparticipants__project__accepted=True,
				  exhibitorparticipants__project__year=getActiveYear(req)) |
				Q(exhibitors__accepted=True,exhibitors__year=getActiveYear(req))
				).distinct(),
			template_name = "mail.html")),
			name="exhibitor_export_adminmail"),
	url(r'export/allmail',
		user_is_staff(EmailOutputView.as_view(
			queryset = lambda req, kwargs : User.objects.filter(
				Q(exhibitorparticipants__project__accepted=True,
				  exhibitorparticipants__project__year=getActiveYear(req)) |
				Q(exhibitors__accepted=True,exhibitors__year=getActiveYear(req))
				).distinct(),
			template_name = "mail.html")),
			name="exhibitor_export_allmail"),
	url(r'^export/xml',
		user_is_staff(YSXMLListView.as_view(
			queryset = Exhibitor.objects.select_related().filter(accepted=True),
			template_name = "exhibitor/xmlexport.html")),
			name="exhibitor_export_xml"),
]

sabot/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from main.views import OverviewView, WayfinderView
from sabot.multiYear import setActiveYearView

from djangosaml2 import views as djangosaml2_views

urlpatterns = [
############# PORTAL PAGE #################

	url(r"^$", 	login_required(WayfinderView.as_view()), name = "homepage"),
	url(r"^overview$",
		login_required(OverviewView.as_view(
			template_name = "main/homepage.html")),
		name = "overview"),
	url(r"^faq$", TemplateView.as_view(template_name="sponsor/publicFaqPage.html")),

########## MULTIYEAR SUPPORT #############
	url(r"^setYear/(?P<year>\d{4})$", login_required(setActiveYearView)),

############ INCLUDE APPS ################
	url(r'^accounts/', include('account.urls')),
	url(r'^accounts/', include('registration.backends.model_activation.urls')),

	url(r'^sponsors/', include('sponsor.urls_sponsors')),
	url(r'^parcel/', include('parcel.urls')),
	url(r'^sponsorcontacts/', include('sponsor.urls_sponsorcontacts')),
	url(r'^sponsorpackages/', include('sponsor.urls_sponsorpackages')),
	url(r'^sponsordjangotemplates/', include('sponsor.urls_sponsordjangotemplates')),
	url(r'^sponsormails/', include('sponsor.urls_sponsormails')),
	url(r'^sponsormailattachments/', include('sponsor.urls_sponsormailattachments')),
	url(r'^projects/', include('project.urls')),
	url(r'^devrooms/', include('devroom.urls')),
	#url(r'^ticket/', include('ticket.urls')),
	url(r'^documenttemplate/', include('invoice.urls_documenttemplate')),
	url(r'^invoice/', include('invoice.urls_invoice')),
	url(r'^saml2/', include('djangosaml2.urls')),
	url(r'^saml2test/', djangosaml2_views.echo_attributes, name='echo_attributes'),
	url(r"^logged_out$", TemplateView.as_view(template_name="registration/logout.html")),
	url(r'^i18n/', include('django.conf.urls.i18n')),
]

if settings.LOCAL:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	from django.contrib.staticfiles.urls import staticfiles_urlpatterns
	urlpatterns += staticfiles_urlpatterns()

exhibitor/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from multiselectfield import MultiSelectField

PREFERENCES = (
        (1, "Main Floor"),
        (2, "Stage"),
        (0, "No preference"),
)

AREAS = (
        (1, "3D Printing"),
        (2, "Arduino"),
        (3, "Art"),
        (4, "Biohacking"),
        (5, "Bionics"),
        (6, "Crafts"),
        (7, "Design"),
        (8, "Digital Fabrication"),
        (9, "Education"),
        (10, "Electronics"),
        (11, "Fashion"),
        (12, "Food & Agriculture"),
        (13, "Garden"),
        (14, "Healthcare"),
        (15, "Home Automation"),
        (16, "Interaction"),
        (17, "Internet of Things"),
        (18, "Model Making"),
        (19, "New Materials"),
        (20, "Raspberry Pi"),
        (21, "Robot & Drones"),
        (22, "Science"),
        (23, "Social design"),
        (24, "Sustainability"),
        (25, "Startup / Small Business"),
        (26, "Tiny Houses"),
        (27, "Transportation"),
        (28, "Wearables"),
        (29, "Wellness"),
        (30, "Young Makers"),
        (31, "Other"),
)

class Exhibitor(models.Model):
	owner = models.ForeignKey(User,editable=False,related_name="exhibitors")
	createDate = models.DateField(auto_now_add=True,editable=False)
	modifyDate = models.DateField(auto_now=True, editable=False)
	projectName = models.CharField(max_length=128, verbose_name=_("Project name"))
	logo = models.ImageField(blank=True,upload_to="exhibitors/logos", verbose_name=_("Project logo"))
	homepage = models.URLField(blank=True, verbose_name=_("Project homepage url"))

	descriptionDE = models.TextField(blank=True, verbose_name=_("Description text of your project (German)"))
	descriptionEN = models.TextField(blank=True, verbose_name=_("Description text of your project (English)"))


	boothPreferedLocation = models.PositiveIntegerField(choices=PREFERENCES, verbose_name=_("Do you have a preferred location for your booth?"), default=0)
	boothNumTables = models.PositiveIntegerField(blank=True,null=True, verbose_name=_("How many tables do you need (roughly 1.20m x 0.80m)?"))
	boothNumChairs = models.PositiveIntegerField(blank=True,null=True, verbose_name=_("How many chairs do you need?"))
        boothPower = models.PositiveIntegerField(blank=True,null=True, verbose_name=_("Do you need power? (How many kwH)"))
        boothArea = MultiSelectField(choices=AREAS, max_length=3, max_choices=3, verbose_name=_("Which area is your booth in?"))
        boothComment = models.TextField(blank=True, verbose_name=_("Here you have the chance to leave us further comments regarding your booth:"))

	participants = models.ManyToManyField(User,blank=True,editable=False,related_name="exhibitorparticipation", through="ExhibitorParticipants")
	accepted = models.BooleanField(default=False, editable=False)

	year = models.PositiveIntegerField(editable=False, verbose_name=_("Conference year this exhibitor belongs to"))

	def has_read_permission(self, user):
		return ExhibitorParticipants.objects.filter(user=user).count() > 0 or user == self.owner

	def has_write_permission(self, user):
		return ExhibitorParticipants.objects.filter(user=user,isAdmin=True).count() > 0 or user == self.owner

class ExhibitorParticipants(models.Model):
	project = models.ForeignKey(Exhibitor)
	user = models.ForeignKey(User)
	isAdmin = models.BooleanField(default=False)

exhibitor/forms.py
from django import forms
from models import Exhibitor
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit, Div, HTML
from crispy_forms.bootstrap import FormActions, StrictButton, TabHolder, Tab

class ExhibitorGeneralForm(forms.ModelForm):
	class Meta:
		model = Exhibitor
		fields = ("projectName", "logo", "homepage")

		widgets = {
			"logo" : forms.widgets.FileInput,
		}

	def __init__(self, *args, **kwargs):
		super(ExhibitorGeneralForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		if self.instance and self.instance.logo:
			self.helper.layout = Layout(
				Field("projectName"),
				Field("logo"),
				Div(
					HTML("<p>Current logo:</p><img src=\"{{object.logo.url}}\" style=\"max-height:200px\"/>"),
					css_class = "control-group"),
				Field("homepage"),
#				FormActions(Submit("Save", "Save changes"))
			)
		else:
			self.helper.layout = Layout(
				Field("projectName"),
				Div(
					Div(Field("logo"),css_class = "col-md-2"),
					css_class = "row"
				),
				Field("homepage"),
#				FormActions(Submit("Save", "{% if object %}Save changes{% else %}Register{% endif %}"))
			)

		if self.instance is not None and self.instance.id is not None:
			self.helper.add_input(Submit("Save", "Save changes"))
		else:
			self.helper.add_input(Submit("Save", "Register"))

class ExhibitorDescriptionForm(forms.ModelForm):
	class Meta:
		model = Exhibitor
		fields = ("descriptionDE", "descriptionEN")

	def __init__(self, *args, **kwargs):
		super(ExhibitorDescriptionForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.layout = Layout(
			Field("descriptionDE"),
			Field("descriptionEN"),
#			FormActions(Submit("Save", "Save changes"))
		)
		self.helper.add_input(Submit("Save","Save changes"))

class ExhibitorBoothForm(forms.ModelForm):
	class Meta:
		model = Exhibitor
		fields = ("boothPreferedLocation", "boothNumTables", "boothNumChairs", "boothPower", "boothArea", "boothComment")

	def __init__(self, *args, **kwargs):
		super(ExhibitorBoothForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.layout = Layout(
			Field("boothPreferedLocation"),
			Field("boothNumTables"),
			Field("boothNumChairs"),
                        Field("boothPower"),
                        Field("boothArea"),
			Div("boothComment", HTML("{% if user.is_staff %} <p>Admin only</p> {% endif %}")),
#			FormActions(Submit("Save", "Save changes"))
		)
		self.helper.add_input(Submit("Save","Save changes"))

exhibitor/views.py
# Create your views here.

templates/exhibitor/alltabshead.html
<div class="page-header">
	<h2>Exhibitor <small>{{object.projectName}}</small></h2>
</div>
{% if object.accepted %}
	<div class="alert alert-success">
		Your project was accepted as exhibitor.
	</div>
{% elif object.createDate > reg_deadline_booth %}
	<div class="alert alert-danger">
		Your project was registered on the {{object.createDate|date:"d.m.Y"}}. This was after the registration deadline ({{reg_deadline_booth|date:"d.m.Y"}}). Please note that we may not be able to accept you as exhibitor this year.
	</div>
{% endif %}

templates/exhibitor/booth.html
{% extends "master.html" %}
{% load crispy_forms_tags %}

{% block content %}

{% include "exhibitor/alltabshead.html" %}

<ul class="nav nav-tabs nav-tabs-bordered">
	<li><a href="{% url 'exhibitor_update_general' pk=object.pk %}">General</a><li>
	<li><a href="{% url 'exhibitor_update_texts' pk=object.pk %}">Description texts</a><li>
	<li class="active"><a href="#">Booth</a><li>
	<li><a href="{% url 'exhibitor_participants' pk=object.pk %}">Participants</a><li>
</ul>

<div class="tab-content tab-bordered">
	<div class="tab-pane active" id="booth_info">
		<div class="row">
			<div class="col-md-8">
				<p class="text-info">
					In the last years, we often had the problem that the exhibition area in the mensa was overcrowded. Thus, we decided that booths in the mensa area can only have <strong>either</strong> normal tables <strong>or</strong> bartables. Moreover, we also offer booths in the first floor of the building. Although, there is more space, there might also be less visitors than in the mensa area. Please state your preferred location if you have one. In the case that everyone fits in the mensa area, we will not offer booths in the first floor.
				</p>
			</div>
		</div>
		{% crispy form form.helper%}
	</div>
</div>

{% endblock %}

templates/exhibitor/create.html
{% extends "master.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="page-header">
	<h2>Register a new project</h2>
</div>
{% if date_today > reg_deadline_booth %}
	<div class="alert alert-danger">
		The registration deadline was the {{reg_deadline_booth|date:"d.m.Y"}}. Please contact us by email if you still want to register for a booth. However, we may not be able to accept you as exhibitor this year.
	</div>
{% endif %}

{% crispy form form.helper%}


{% endblock %}

templates/exhibitor/del.html
{% extends "master.html" %}

{% block content %}
<div class="page-header">
	<h2>Confirm deletion</h2>
</div>
<div class="row">
<div class="col-md-3 centerbox">
		<form method="POST">
			{% csrf_token %}
			Do you really want to remove {{object.projectName}}?
			{{form.as_p}}
			<div class="form-actions">
				<button type="Submit" class="btn btn-danger">Delete</button>
				<a href="{% url 'exhibitor_list' %}" class="btn">Cancel</a>
			</div>
		</form>
	</div>
</div>
{% endblock %}

templates/exhibitor/description.html
{% extends "master.html" %}
{% load crispy_forms_tags %}

{% block content %}

{% include "exhibitor/alltabshead.html" %}

<ul class="nav nav-tabs nav-tabs-bordered">
	<li><a href="{% url 'exhibitor_update_general' pk=object.pk %}">General</a><li>
	<li class="active"><a href="#">Description texts</a><li>
	<li><a href="{% url 'exhibitor_update_booth' pk=object.pk %}">Booth</a><li>
	<li><a href="{% url 'exhibitor_participants' pk=object.pk %}">Participants</a><li>
</ul>

<div class="tab-content tab-bordered">
	<div class="tab-pane active" id="description_info">
		{% crispy form form.helper%}
	</div>
</div>

{% endblock %}

templates/exhibitor/general.html
{% extends "master.html" %}
{% load crispy_forms_tags %}

{% block content %}

{% include "exhibitor/alltabshead.html" %}

<ul class="nav nav-tabs nav-tabs-bordered">
	<li class="active"><a href="#">General</a><li>
	<li><a href="{% url 'exhibitor_update_texts' pk=object.pk %}">Description texts</a><li>
	<li><a href="{% url 'exhibitor_update_booth' pk=object.pk %}">Booth</a><li>
	<li><a href="{% url 'exhibitor_participants' pk=object.pk %}">Participants</a><li>
</ul>

<div class="tab-content tab-bordered">
	<div class="tab-pane active" id="general_info">
		{% crispy form form.helper%}
	</div>
</div>

{% endblock %}

templates/exhibitor/list+planning.html
{% extends "master.html" %}
{% block content %}

<div class="page-header">
	<h2>List of exhibitors ({{object_list|length}})</h2>
</div>
<ul class="nav nav-pills">
	<li>
		<a href="{% url 'exhibitor_list' %}">Information View</a>
	</li>
	<li class="active"><a href="#">Planning View</a></li>
</ul>
<div class="controls">
	<label for="show-only-accepted" class="checkbox"><input id="show-only-accepted" class="checkboxinput" type="checkbox" /> Show only accepted exhibitors</label>
</div>
<table class="table table-striped table-bordered table-hover tablesorter">
	<thead>
		<tr>
			<th>Project name</th>
			<th>Contact</th>
			<th>Location</th>
			<th>Tables</th>
			<th>Chairs</th>
            <th>Power</th>
            <th>Area</th>
			<th>Provided information</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		{% for project in object_list %}
			<tr{% if project.accepted %} class="success"{% elif project.createDate > reg_deadline_booth %} class="danger"{% endif %}>
				<td>{{project.projectName}}</td>
				<td>{{project.owner.first_name}} {{project.owner.last_name}}</td>
				<td>
					{% if project.boothPreferedLocation == 0 %}
						No preference
					{% elif project.boothPreferedLocation == 1 %}
						Mensa
					{% elif project.boothPreferedLocation == 2 %}
						First floor
					{% endif %}
				</td>
				<td>{{project.boothNumTables}}</td>
				<td>{{project.boothNumChairs}}</td>
                <td>{{project.boothPower}}</td>
                <td>{{project.boothArea}}</td>
				<td>
					{% if project.descriptionDE != "" and project.descriptionEN != "" %}<a href="{% url 'exhibitor_update_texts' pk=project.pk %}" data-toggle="tooltip" title="Texts in DE and EN available"><span class="glyphicon glyphicon-globe"></span></a>{% endif %}
					{% if project.boothNumTables and project.boothNumChairs and project.boothPower and project.boothArea %}<a href="{% url 'exhibitor_update_booth' pk=project.pk %}" data-toggle="tooltip" title="Booth information available"><span class="glyphicon glyphicon-home"></span></a>{% endif %}
					{% if project.participants.all %}<a href="{% url 'exhibitor_participants' pk=project.pk %}" data-toggle="tooltip" title="Participants available"><span class="glyphicon glyphicon-user"></span></a>{% endif %}
					<td>
						<a href="{% url 'exhibitor_update_general' pk=project.pk %}" data-toggle="tooltip" title="Edit exhibitor information"><span class="glyphicon glyphicon-edit"></span></a>
					</td>
			</tr>
		{% endfor %}
	</tbody>

</table>

<script>
	$(document).ready(function () {
		$(".tablesorter").tablesorter({ sortList: [[0,0]], headers : { 6 : { sorter: false}}});

		$("#show-only-accepted").change(function () {
			if ($(this).prop("checked")) {
				$("tbody > tr:not(.success)").hide();
			}
			else {
				$("tbody > tr:not(.success)").show();
			}
		});
	});
</script>

{% endblock %}

templates/exhibitor/list.html
{% extends "master.html" %}
{% block content %}

<div class="page-header">
	<h2>List of exhibitors ({{object_list|length}})</h2>
</div>
<ul class="nav nav-pills">
	<li class="active">
		<a href="#">Information View</a>
	</li>
	<li><a href="{% url 'exhibitor_list_planning' %}">Planning View</a></li>
	<li class="pull-right"><a href="{% url 'exhibitor_export_xml' %}" data-toggle="tooltip" title="Download exhibitor data of accepted projects as XML">XML export</a></li>
	<li class="pull-right"><a href="{% url 'exhibitor_export_adminmail' %}" data-toggle="tooltip" title="Download the email addresses of the organizers (people with edit permissions) of all accepted projects">Organizer Mails</a></li>
	<li class="pull-right"><a href="{% url 'exhibitor_export_allmail' %}" data-toggle="tooltip" title="Download the email addresses of all participants of all accepted projects">Participant Mails</a></li>
</ul>
<div class="controls">
	<label for="show-only-accepted" class="checkbox"><input id="show-only-accepted" class="checkboxinput" type="checkbox" /> Show only accepted exhibitors</label>
</div>
<table class="table table-striped table-bordered table-hover tablesorter">
	<thead>
		<tr>
			<th>Project name</th>
			<th>Main Contact</th>
			<th>E-Mail</th>
			<th>Provided information</th>
			<th>Last modified</th>
			<th>Creation date</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		{% for project in object_list %}
			<tr{% if project.accepted %} class="success"{% elif project.createDate > reg_deadline_booth %} class="danger"{% endif %}>
				<td>{{project.projectName}}</td>
				<td>{{project.owner.first_name}} {{project.owner.last_name}}</td>
				<td>{{project.owner.email}}</td>
				<td>
					{% if project.descriptionDE != "" and project.descriptionEN != "" %}<a href="{% url 'exhibitor_update_texts' pk=project.pk %}" data-toggle="tooltip" title="Texts in DE and EN available"><span class="glyphicon glyphicon-globe"></span></a>{% endif %}
					{% if project.boothNumTables and project.boothNumChairs and project.boothPower and project.boothArea %}<a href="{% url 'exhibitor_update_booth' pk=project.pk %}" data-toggle="tooltip" title="Booth information available"><span class="glyphicon glyphicon-home"></span></a>{% endif %}
					{% if project.participants.all %}<a href="{% url 'exhibitor_participants' pk=project.pk %}" data-toggle="tooltip" title="Participants available"><span class="glyphicon glyphicon-user"></span></a>{% endif %}
				</td>
				<td>{{project.modifyDate|date:"j.n.Y"}}</td>
				<td>{{project.createDate|date:"j.n.Y"}}</td>
				<td>
					{% if project.accepted %}
						<form action="{% url 'exhibitor_unaccept' pk=project.pk %}" method="POST" style="display: inline">
							{% csrf_token %}
							<label for="unaccept-{{project.pk}}" style="display: inline"><span data-toggle="tooltip" title="Set this exhibitor to not accepted" class="glyphicon glyphicon-thumbs-down"></i></label>
							<input type="submit" id="unaccept-{{project.pk}}" style="display: None" />
						</form>
					{% else %}
						<form action="{% url 'exhibitor_accept' pk=project.pk %}" method="POST" style="display: inline">
							{% csrf_token %}
							<label for="accept-{{project.pk}}" style="display: inline"><span data-toggle="tooltip" title="Accept this exhibitor" class="glyphicon glyphicon-thumbs-up"></span></label>
							<input type="submit" id="accept-{{project.pk}}" style="display: None" />
						</form>
					{% endif %}
					<a href="{% url 'exhibitor_update_general' pk=project.pk %}" data-toggle="tooltip" title="Edit exhibitor information"><span class="glyphicon glyphicon-edit"></span></a>
					<a href="{% url 'exhibitor_del' pk=project.pk %}" data-toggle="tooltip" title="Delete this exhibitor"><span class="glyphicon glyphicon-remove"></span></a>
				</td>
			</tr>
		{% endfor %}
	</tbody>

</table>

<script>
	$(document).ready(function () {
		$(".tablesorter").tablesorter({ sortList: [[0,0]], headers : { 3 : { sorter: false}, 6 : {sorter : false}, 4 : {sorter : "eudate"}, 5 : {sorter : "eudate"}}});

		$("#show-only-accepted").change(function () {
			if ($(this).prop("checked")) {
				$("tbody > tr:not(.success)").hide();
			}
			else {
				$("tbody > tr:not(.success)").show();
			}
		});
	});
</script>

{% endblock %}

templates/exhibitor/xmlexport.html
<?xml version="1.0" encoding="UTF-8"?>
<exhibitors xmlns="{{INSTALL_MAIN_URL}}/exhibitors">
	{% for project in object_list %}
		<exhibitor>
			<name>{{project.projectName}}</name>
			<creationDate>{{project.createDate|date:"U"}}</creationDate>
			<lastModified>{{project.modifyDate|date:"U"}}</lastModified>
			<maincontact>
				<firstname>{{project.owner.first_name}}</firstname>
				<lastname>{{project.owner.last_name}}</lastname>
				<email>{{project.owner.email}}</email>
			</maincontact>
			<homepage>{{project.homepage}}</homepage>
			{% if project.logo %}<logo>{{project.logo.url}}</logo>{% endif %}
			<description lang="en">
				{{project.descriptionEN}}
			</description>
			<description lang="de">
				{{project.descriptionDE}}
			</description>
			<booth>
            <preferredLocation>{{project.boothPreferedLocation}}</preferredLocation>
				<tables>{{project.boothNumTables}}</tables>
				<chairs>{{project.boothNumChairs}}</chairs>
                <power>{{project.boothPower}}</power>
                <area>{{project.boothArea}}</area>
				<comment>{{project.boothComment}}</comment>
			</booth>
			<participants>
				{% for membership in project.exhibitorparticipants_set.all %}
					<person>
						<firstname>{{membership.user.first_name}}</firstname>
						<lastname>{{membership.user.last_name}}</lastname>
						<email>{{membership.user.email}}</email>
						{% if membership.isAdmin %}<organizer />{% endif %}
					</person>
				{% endfor %}
			</participants>
		</exhibitor>
	{% endfor %}
</exhibitors>